### ISSUE TITLE
Redis Connection Error 111 to port 6397 when running the loaddata script

### ISSUE THREAD

**Issue by mina-andajos** [LesFruitsDefendus/saskatoon-ng#142]
After running:
```bash
python3 saskatoon/manage.py loaddata saskatoon/fixtures/saskatoon.json
```

I get this connection error (last line in the output):
```bash
redis.exceptions.ConnectionError: Problem installing fixture 'saskatoon-ng/saskatoon/fixtures/saskatoon.json': Error 111 connecting to 127.0.0.1:6379. Connection refused.
```
Which fixtures are not affected by this error so they can be loaded, or unload redis as a workaround?

**Comment by mina-andajos** [comment]
Full command output:
```bash
❯ python3 saskatoon/manage.py loaddata saskatoon/fixtures/saskatoon.json
Traceback (most recent call last):
  File "/home/pure-cheekbones/anaconda3/lib/python3.9/site-packages/django_redis/cache.py", line 31, in _decorator
    return method(self, *args, **kwargs)
  File "/home/pure-cheekbones/anaconda3/lib/python3.9/site-packages/django_redis/cache.py", line 109, in delete_pattern
    return self.client.delete_pattern(*args, **kwargs)
  File "/home/pure-cheekbones/anaconda3/lib/python3.9/site-packages/django_redis/client/default.py", line 401, in delete_pattern
    raise ConnectionInterrupted(connection=client) from e
django_redis.exceptions.ConnectionInterrupted: Redis ConnectionError: Problem installing fixture '/mnt/d/niabc/Programming/Outreachy/Contributions/SASKATOON-NG/saskatoon-ng/saskatoon/fixtures/saskatoon.json': Error 111 connecting to 127.0.0.1:6379. Connection refused.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/d/niabc/Programming/Outreachy/Contributions/SASKATOON-NG/saskatoon-ng/saskatoon/manage.py", line 21, in <module>
    main()
  File "/mnt/d/niabc/Programming/Outreachy/Contributions/SASKATOON-NG/saskatoon-ng/saskatoon/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/pure-cheekbones/anaconda3/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/pure-cheekbones/anaconda3/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/pure-cheekbones/anaconda3/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/pure-cheekbones/anaconda3/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/pure-cheekbones/anaconda3/lib/python3.9/site-packages/django/core/management/commands/loaddata.py", line 78, in handle
    self.loaddata(fixture_labels)
  File "/home/pure-cheekbones/anaconda3/lib/python3.9/site-packages/django/core/management/commands/loaddata.py", line 123, in loaddata
    self.load_label(fixture_label)
  File "/home/pure-cheekbones/anaconda3/lib/python3.9/site-packages/django/core/management/commands/loaddata.py", line 190, in load_label
    obj.save(using=self.using)
  File "/home/pure-cheekbones/anaconda3/lib/python3.9/site-packages/django/core/serializers/base.py", line 223, in save
    models.Model.save_base(self.object, using=using, raw=True, **kwargs)
  File "/home/pure-cheekbones/anaconda3/lib/python3.9/site-packages/django/db/models/base.py", line 774, in save_base
    post_save.send(
  File "/home/pure-cheekbones/anaconda3/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 180, in send
    return [
  File "/home/pure-cheekbones/anaconda3/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/mnt/d/niabc/Programming/Outreachy/Contributions/SASKATOON-NG/saskatoon-ng/saskatoon/harvest/signals.py", line 7, in clear_cache_property
    cache.delete_pattern("*property*")
  File "/home/pure-cheekbones/anaconda3/lib/python3.9/site-packages/django_redis/cache.py", line 38, in _decorator
    raise e.__cause__
  File "/home/pure-cheekbones/anaconda3/lib/python3.9/site-packages/django_redis/client/default.py", line 396, in delete_pattern
    for key in client.scan_iter(match=pattern, count=itersize):
  File "/home/pure-cheekbones/anaconda3/lib/python3.9/site-packages/redis/commands/core.py", line 2826, in scan_iter
    cursor, data = self.scan(
  File "/home/pure-cheekbones/anaconda3/lib/python3.9/site-packages/redis/commands/core.py", line 2801, in scan
    return self.execute_command("SCAN", *pieces, **kwargs)
  File "/home/pure-cheekbones/anaconda3/lib/python3.9/site-packages/redis/client.py", line 1192, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/home/pure-cheekbones/anaconda3/lib/python3.9/site-packages/redis/connection.py", line 1386, in get_connection
    connection.connect()
  File "/home/pure-cheekbones/anaconda3/lib/python3.9/site-packages/redis/connection.py", line 620, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Problem installing fixture '/mnt/d/niabc/Programming/Outreachy/Contributions/SASKATOON-NG/saskatoon-ng/saskatoon/fixtures/saskatoon.json': Error 111 connecting to 127.0.0.1:6379. Connection refused.
```

**Comment by mina-andajos** [comment]
I also get this error when I try to fill a property both using the site, and the admin panel (I used #138)

**Comment by mina-andajos** [comment]
`reddis-server.service` haven't started for me which caused the issue.
