### ISSUE TITLE
Fix django.db.utils.IntegrityError: FOREIGN KEY constraint failed loading init fixures

### ISSUE THREAD

**Issue by tristanlatr** [LesFruitsDefendus/saskatoon-ng#268]
The workaround would be to re-generate all the fixtures.

```
$ saskatoon/fixtures/init
...
Loading harvest-property
Installed 2 object(s) from 1 fixture(s)
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/django/db/backends/base/base.py", line 242, in _commit
    return self.connection.commit()
sqlite3.IntegrityError: FOREIGN KEY constraint failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "../manage.py", line 21, in <module>
    main()
  File "../manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/django/core/management/commands/loaddata.py", line 78, in handle
    self.loaddata(fixture_labels)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/django/db/transaction.py", line 246, in __exit__
    connection.commit()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/django/utils/asyncio.py", line [33](https://github.com/LesFruitsDefendus/saskatoon-ng/runs/6042521691?check_suite_focus=true#step:12:33), in inner
    return func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/django/db/backends/base/base.py", line 266, in commit
    self._commit()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/django/db/backends/base/base.py", line 2[42](https://github.com/LesFruitsDefendus/saskatoon-ng/runs/6042521691?check_suite_focus=true#step:12:42), in _commit
    return self.connection.commit()
  File "/opt/hostedtoolcache/Python/3.8.12/x[64](https://github.com/LesFruitsDefendus/saskatoon-ng/runs/6042521691?check_suite_focus=true#step:12:64)/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/django/db/backends/base/base.py", line 242, in _commit
    return self.connection.commit()
django.db.utils.IntegrityError: FOREIGN KEY constraint failed
```

**Comment by 2ynn** [comment]
@tristanlatr I found the issue

The property depends on TreeType (property 3 has trees 9 and 14), so `harvest-treetype` must be loaded before `harvest-property`

![screenshot_2022-04-15_19:03:05](https://user-images.githubusercontent.com/41802320/163650969-ba6be928-7ce5-4c07-9872-564664c46e7e.png)

Can you please test and add the change? Thanks!

**Comment by tristanlatr** [comment]
It worked! Thanks @2ynn :)
