### ISSUE TITLE
Installation issue 

### ISSUE THREAD

**Issue by tristanlatr** [LesFruitsDefendus/saskatoon-ng#41]
Hi @tiagovaz ,

Creating an issue to track the installation process issue I'm getting when trying got instal saskatoon-ng on my mac with virtualenv. 

Once we get this working, I'll try to have some basic CI testing setup, like with `tox` and `mypy`, `pytype`, `pyflakes` (and, of course, the unit tests when we have them written)

When following the INSTALL.md:

Here is the traceback I'm getting when trying to initiate the database.

I see that the older version of saskatoon as tiagovaz/saskatoon@master has some migration files, do we need those as well ?

```
$ python manage.py migrate
Traceback (most recent call last):
  File "/Users/landestt/Documents/isrm-git/saskatoon-ng/ve/lib/python3.9/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/landestt/Documents/isrm-git/saskatoon-ng/ve/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 396, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: harvest_harvest

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/landestt/Documents/isrm-git/saskatoon-ng/saskatoon/manage.py", line 21, in <module>
    main()
  File "/Users/landestt/Documents/isrm-git/saskatoon-ng/saskatoon/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/Users/landestt/Documents/isrm-git/saskatoon-ng/ve/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/landestt/Documents/isrm-git/saskatoon-ng/ve/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/landestt/Documents/isrm-git/saskatoon-ng/ve/lib/python3.9/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/landestt/Documents/isrm-git/saskatoon-ng/ve/lib/python3.9/site-packages/django/core/management/base.py", line 366, in execute
    self.check()
  File "/Users/landestt/Documents/isrm-git/saskatoon-ng/ve/lib/python3.9/site-packages/django/core/management/base.py", line 392, in check
    all_issues = self._run_checks(
  File "/Users/landestt/Documents/isrm-git/saskatoon-ng/ve/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 64, in _run_checks
    issues.extend(super()._run_checks(**kwargs))
  File "/Users/landestt/Documents/isrm-git/saskatoon-ng/ve/lib/python3.9/site-packages/django/core/management/base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "/Users/landestt/Documents/isrm-git/saskatoon-ng/ve/lib/python3.9/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Users/landestt/Documents/isrm-git/saskatoon-ng/ve/lib/python3.9/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/Users/landestt/Documents/isrm-git/saskatoon-ng/ve/lib/python3.9/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/Users/landestt/Documents/isrm-git/saskatoon-ng/ve/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/landestt/Documents/isrm-git/saskatoon-ng/ve/lib/python3.9/site-packages/django/urls/resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/landestt/Documents/isrm-git/saskatoon-ng/ve/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/landestt/Documents/isrm-git/saskatoon-ng/ve/lib/python3.9/site-packages/django/urls/resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/landestt/Documents/isrm-git/saskatoon-ng/saskatoon/saskatoon/urls.py", line 6, in <module>
    path('', include('harvest.urls')),
  File "/Users/landestt/Documents/isrm-git/saskatoon-ng/ve/lib/python3.9/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/landestt/Documents/isrm-git/saskatoon-ng/saskatoon/harvest/urls.py", line 5, in <module>
    from . import api
  File "/Users/landestt/Documents/isrm-git/saskatoon-ng/saskatoon/harvest/api.py", line 5, in <module>
    from harvest.filters import HarvestFilter, PropertyFilter
  File "/Users/landestt/Documents/isrm-git/saskatoon-ng/saskatoon/harvest/filters.py", line 10, in <module>
    class HarvestFilter(filters.FilterSet):
  File "/Users/landestt/Documents/isrm-git/saskatoon-ng/saskatoon/harvest/filters.py", line 12, in HarvestFilter
    for y in Harvest.objects.all():
  File "/Users/landestt/Documents/isrm-git/saskatoon-ng/ve/lib/python3.9/site-packages/django/db/models/query.py", line 276, in __iter__
    self._fetch_all()
  File "/Users/landestt/Documents/isrm-git/saskatoon-ng/ve/lib/python3.9/site-packages/django/db/models/query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/landestt/Documents/isrm-git/saskatoon-ng/ve/lib/python3.9/site-packages/django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/Users/landestt/Documents/isrm-git/saskatoon-ng/ve/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1152, in execute_sql
    cursor.execute(sql, params)
  File "/Users/landestt/Documents/isrm-git/saskatoon-ng/ve/lib/python3.9/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/Users/landestt/Documents/isrm-git/saskatoon-ng/ve/lib/python3.9/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/landestt/Documents/isrm-git/saskatoon-ng/ve/lib/python3.9/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/landestt/Documents/isrm-git/saskatoon-ng/ve/lib/python3.9/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/landestt/Documents/isrm-git/saskatoon-ng/ve/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/landestt/Documents/isrm-git/saskatoon-ng/ve/lib/python3.9/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/landestt/Documents/isrm-git/saskatoon-ng/ve/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 396, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: harvest_harvest
```

**Comment by tiagovaz** [comment]
The code indeed tries to access the database during the migration processing (before the table is created), I'm trying to find where is the issue.

**Comment by tiagovaz** [comment]
It was in the filters. We just need to skip checks during migration. I added that option in INSTALL. I'm working on next steps for the installation process.
