### ISSUE TITLE
Something is broken: django.db.utils.OperationalError: no such table: harvest_harvest

### ISSUE THREAD

**Issue by tristanlatr** [LesFruitsDefendus/saskatoon-ng#67]
Here is the steps I took to reproduce the error, I'm just following the `INSTALL.md`: 

```
(ve) tristan@qqul105fs saskatoon-ng % pip install .
Processing /Users/tristan/Documents/saskatoon-ng
Collecting asgiref>=3.2.7
  Using cached asgiref-3.3.4-py3-none-any.whl (22 kB)
Collecting cffi==1.14.0
  Using cached cffi-1.14.0-cp38-cp38-macosx_10_9_x86_64.whl (175 kB)
Collecting cryptography>=3.3.2
  Using cached cryptography-3.4.7-cp36-abi3-macosx_10_10_x86_64.whl (2.0 MB)
Collecting Django>=3.0.14
  Using cached Django-3.2-py3-none-any.whl (7.9 MB)
Collecting django-geojson==3.0.0
  Using cached django_geojson-3.0.0-py3-none-any.whl
Collecting django-leaflet==0.26.0
  Using cached django_leaflet-0.26.0-py3-none-any.whl
Collecting django-rest-knox==4.1.0
  Using cached django_rest_knox-4.1.0-py3-none-any.whl (13 kB)
Collecting djangorestframework>=3.11.0
  Using cached djangorestframework-3.12.4-py3-none-any.whl (957 kB)
Collecting django-autocomplete-light>=3.8.2
  Using cached django_autocomplete_light-3.8.2-py3-none-any.whl
Collecting django-select2
  Downloading django_select2-7.7.1-py2.py3-none-any.whl (14 kB)
Collecting django-ckeditor
  Using cached django_ckeditor-6.0.0-py2.py3-none-any.whl (2.4 MB)
Collecting django-filter
  Using cached django_filter-2.4.0-py3-none-any.whl (73 kB)
Collecting django-bootstrap3
  Downloading django_bootstrap3-15.0.0-py3-none-any.whl (213 kB)
     |████████████████████████████████| 213 kB 1.2 MB/s 
Collecting django-bootstrap-form
  Using cached django_bootstrap_form-3.4-py2.py3-none-any.whl
Collecting django-crequest
  Using cached django_crequest-2018.5.11-py3-none-any.whl
Collecting jsonfield==3.1.0
  Using cached jsonfield-3.1.0-py3-none-any.whl (8.0 kB)
Collecting mysqlclient==1.4.6
  Using cached mysqlclient-1.4.6-cp38-cp38-macosx_10_15_x86_64.whl
Collecting Pillow==8.1.1
  Using cached Pillow-8.1.1-cp38-cp38-macosx_10_10_x86_64.whl (2.2 MB)
Collecting pycparser==2.20
  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
Collecting pytz==2020.1
  Using cached pytz-2020.1-py2.py3-none-any.whl (510 kB)
Collecting six==1.15.0
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting sqlparse==0.3.1
  Using cached sqlparse-0.3.1-py2.py3-none-any.whl (40 kB)
Collecting django-redis
  Using cached django_redis-4.12.1-py3-none-any.whl (19 kB)
Collecting python-dotenv
  Using cached python_dotenv-0.17.0-py2.py3-none-any.whl (18 kB)
Collecting django-js-asset>=1.2.2
  Using cached django_js_asset-1.2.2-py2.py3-none-any.whl (5.8 kB)
Collecting redis>=3.0.0
  Using cached redis-3.5.3-py2.py3-none-any.whl (72 kB)
Collecting django-appconf>=0.6.0
  Using cached django_appconf-1.0.4-py2.py3-none-any.whl (6.3 kB)
Building wheels for collected packages: Saskatoon
  Building wheel for Saskatoon (setup.py) ... done
  Created wheel for Saskatoon: filename=Saskatoon-2.dev0-py3-none-any.whl size=13469 sha256=8b15a49624d3f78ef94e1d69ad81f5fec580a49d0727519e86b6838515e129e0
  Stored in directory: /Users/tristan/Library/Caches/pip/wheels/d1/f2/7a/7f060b8240863665835aeab284bf292b343b6c867bfd674d2c
Successfully built Saskatoon
Installing collected packages: sqlparse, pytz, pycparser, asgiref, Django, cffi, six, redis, djangorestframework, django-js-asset, django-appconf, cryptography, python-dotenv, Pillow, mysqlclient, jsonfield, django-select2, django-rest-knox, django-redis, django-leaflet, django-geojson, django-filter, django-crequest, django-ckeditor, django-bootstrap3, django-bootstrap-form, django-autocomplete-light, Saskatoon
Successfully installed Django-3.2 Pillow-8.1.1 Saskatoon-2.dev0 asgiref-3.3.4 cffi-1.14.0 cryptography-3.4.7 django-appconf-1.0.4 django-autocomplete-light-3.8.2 django-bootstrap-form-3.4 django-bootstrap3-15.0.0 django-ckeditor-6.0.0 django-crequest-2018.5.11 django-filter-2.4.0 django-geojson-3.0.0 django-js-asset-1.2.2 django-leaflet-0.26.0 django-redis-4.12.1 django-rest-knox-4.1.0 django-select2-7.7.1 djangorestframework-3.12.4 jsonfield-3.1.0 mysqlclient-1.4.6 pycparser-2.20 python-dotenv-0.17.0 pytz-2020.1 redis-3.5.3 six-1.15.0 sqlparse-0.3.1
(ve) tristan@qqul105fs saskatoon-ng % python3 saskatoon/manage.py migrate --skip-checks
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying sessions.0001_initial... OK
(ve) tristan@qqul105fs saskatoon-ng % python3 saskatoon/manage.py createsuperuser
Traceback (most recent call last):
  File "/Users/tristan/Documents/saskatoon-ng/ve/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/tristan/Documents/saskatoon-ng/ve/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: harvest_harvest

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "saskatoon/manage.py", line 21, in <module>
    main()
  File "saskatoon/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/Users/tristan/Documents/saskatoon-ng/ve/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/Users/tristan/Documents/saskatoon-ng/ve/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/tristan/Documents/saskatoon-ng/ve/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/tristan/Documents/saskatoon-ng/ve/lib/python3.8/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 79, in execute
    return super().execute(*args, **options)
  File "/Users/tristan/Documents/saskatoon-ng/ve/lib/python3.8/site-packages/django/core/management/base.py", line 393, in execute
    self.check()
  File "/Users/tristan/Documents/saskatoon-ng/ve/lib/python3.8/site-packages/django/core/management/base.py", line 419, in check
    all_issues = checks.run_checks(
  File "/Users/tristan/Documents/saskatoon-ng/ve/lib/python3.8/site-packages/django/core/checks/registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/Users/tristan/Documents/saskatoon-ng/ve/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/Users/tristan/Documents/saskatoon-ng/ve/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/Users/tristan/Documents/saskatoon-ng/ve/lib/python3.8/site-packages/django/urls/resolvers.py", line 412, in check
    for pattern in self.url_patterns:
  File "/Users/tristan/Documents/saskatoon-ng/ve/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/tristan/Documents/saskatoon-ng/ve/lib/python3.8/site-packages/django/urls/resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/tristan/Documents/saskatoon-ng/ve/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/tristan/Documents/saskatoon-ng/ve/lib/python3.8/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/Cellar/python@3.8/3.8.7_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/tristan/Documents/saskatoon-ng/saskatoon/saskatoon/urls.py", line 6, in <module>
    path('', include('harvest.urls')),
  File "/Users/tristan/Documents/saskatoon-ng/ve/lib/python3.8/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/Cellar/python@3.8/3.8.7_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/tristan/Documents/saskatoon-ng/saskatoon/harvest/urls.py", line 3, in <module>
    from . import api
  File "/Users/tristan/Documents/saskatoon-ng/saskatoon/harvest/api.py", line 9, in <module>
    from harvest.filters import HarvestFilter, PropertyFilter, CommunityFilter
  File "/Users/tristan/Documents/saskatoon-ng/saskatoon/harvest/filters.py", line 12, in <module>
    class HarvestFilter(filters.FilterSet):
  File "/Users/tristan/Documents/saskatoon-ng/saskatoon/harvest/filters.py", line 14, in HarvestFilter
    for y in Harvest.objects.all():
  File "/Users/tristan/Documents/saskatoon-ng/ve/lib/python3.8/site-packages/django/db/models/query.py", line 280, in __iter__
    self._fetch_all()
  File "/Users/tristan/Documents/saskatoon-ng/ve/lib/python3.8/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/tristan/Documents/saskatoon-ng/ve/lib/python3.8/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/Users/tristan/Documents/saskatoon-ng/ve/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1169, in execute_sql
    cursor.execute(sql, params)
  File "/Users/tristan/Documents/saskatoon-ng/ve/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/Users/tristan/Documents/saskatoon-ng/ve/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/tristan/Documents/saskatoon-ng/ve/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/tristan/Documents/saskatoon-ng/ve/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/tristan/Documents/saskatoon-ng/ve/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/tristan/Documents/saskatoon-ng/ve/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/tristan/Documents/saskatoon-ng/ve/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: harvest_harvest
```

**Comment by tristanlatr** [comment]
It looks like importing `HarvestFilter` have side effects such that it tries to iterate over `Harvest.objects.all()`. 

If I understand correctly, it initiate the values of `HarvestFilter.seasons` based on the dates of the picks on the database at a moment when the database has not been initiated yet. 

The import line in `api.py`: 
```python
from harvest.filters import HarvestFilter
```
It's been a while that this import is present in the file, so I don't know what is the root cause of the issue...

This occurs when launching command `python3 saskatoon/manage.py createsuperuser` after a successful `python3 saskatoon/manage.py migrate --skip-checks` on a clean install. 

@tiagovaz , Can you reproduce the issue ?

**Comment by tiagovaz** [comment]
Hi @tristanlatr, I had a look and it seems the problem is with the missing migrations. If you check the output, you'll see that no harvest nor member models have been migrated. 

You're right about the harvestfilter issue, but this one we can workaround with --skip-checks

I've added the migrations files to git and tried here and worked. Now we need to create some fixtures and hopefully anyone will be able to deploy it, finally.

**Comment by tristanlatr** [comment]
It's working! :D
